language: ruby
rvm:
  - 2.3.1
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  # consider dumping sql via db:structure:dump then loading directly into psql
  # "psql -U postgres -q -d DB_NAME -f db/structure.sql"
  - bundle exec rake assets:precompile
  - bundle exec rake db:test:prepare
script: bundle exec rake i18n
env: RAILS_ENV=test
dist: trusty
sudo: required
