development:
  enabled: false
  host: bikebike.org

preview:
  enabled: false
  host: preview-cdn.bikebike.org
  protocol: https
  fallback_protocol: http

production:
  enabled: true
  host: cdn.bikebike.org
  protocol: https
  fallback_protocol: http
