development:
  username: goodgodwin-facilitator_api1.hotmail.com
  password: 1364499062
  signature: A8ydvWJ4VGIEPgYhKlCiqbJ7KrGvATclp5xDn-IKlmSUFXGwcA62ZT82

test:
  username: goodgodwin-facilitator_api1.hotmail.com
  password: 1364499062
  signature: A8ydvWJ4VGIEPgYhKlCiqbJ7KrGvATclp5xDn-IKlmSUFXGwcA62ZT82
