---
:concurrency: 5
:logfile: log/sidekiq.log
preview:
  :pidfile: /home/unicorn/sidekiq_preview.pid
  :concurrency: 15
  :queues:
    - preview
production:
  :pidfile: /home/unicorn/sidekiq_production.pid
  :concurrency: 15
  :queues:
    - production
